### ISSUE TITLE
Any easy way on how can I test it locally?

### ISSUE THREAD

**Issue by zkanda** [eawsy/aws-lambda-go-shim#14]
Hi,

Thank you so much for creating this package, is there an easy way to test my function locally?
E.g.:
Passing a `json` like in the event.

Cheers!

**Comment by fsenart** [comment]
Hi @zkanda,

For now we do not provide any tool for such purposes but you still have all the power of Golang plugins:

```go
package main

import (
	"encoding/json"
	"log"
	"os"

	"github.com/eawsy/aws-lambda-go-core/service/lambda/runtime"
)

func Handle(evt map[string]interface{}, ctx *runtime.Context) (interface{}, error) {
	return evt, nil
}

func main() {
	dec := json.NewDecoder(os.Stdin)
	enc := json.NewEncoder(os.Stdout)
	var v map[string]interface{}
	if err := dec.Decode(&v); err != nil {
		log.Fatal(err)
	}
	r, err := Handle(v, nil)
	if err != nil {
		log.Fatal(err)
	}
	if err := enc.Encode(&r); err != nil {
		log.Fatal(err)
	}
}
```
```sh
echo '{"Foo": "Bar"}' | go run handler.go
```

One cool thing with Go plugins is that the `main` function is not taken into account when the final build takes place; but this function is called as usual when using `go run`. So as showed above, and depending on your problem you can achieve local testing pretty easily. 

PS: Otherwise, I tend to advocate the usage of standard unit tests for local testing.

**Comment by zkanda** [comment]
Right! I'm using the `main` function as of now and I agree, standard unit test is the way to go.

Thanks again, cheers!

**Comment by alexaandru** [comment]
FWIW, https://github.com/awslabs/aws-sam-local works great for testing things locally. It's as close as the real thing as you can get (will run the .zip via the Python runtime, you can set memory/timeout constraints, etc.).
