### ISSUE TITLE
Is It possible to call CGO?

### ISSUE THREAD

**Issue by grafael** [eawsy/aws-lambda-go-shim#18]
Is it possible to call Golang CGO routines?

**Comment by fsenart** [comment]
Hi @grafael,

Can you please provide more detail? Do you mean calling the shim CGO functions? or your own CGO functions?

**Comment by grafael** [comment]
I mean my own CGO functions. I am asking that because the Google app engine (Google cloud platform) does not support, and I was wondering to use aws lambda.

**Comment by fsenart** [comment]
In theory I don't see any problem preventing you from doing such calls. I haven't tested such calls but it should be ok. 
One thing to notice, in order to compile your CGO parts, you have to be in the same environment than AWS Lambda, so you should use https://hub.docker.com/_/amazonlinux/ image or our docker image which embed this one. 
I'll be glad to hear back from you to know if this scenario is possible. And do not hesitate if you encounter any problem, create an ephemeral repo and I'll assist you.

**Comment by grafael** [comment]
Thanks. I'll try that soon, and  I let you know the results

**Comment by fsenart** [comment]
:wink: I'll close the issue for now, but feel free to continue the thread if you have any other question.
