### ISSUE TITLE
how to use environment variable

### ISSUE THREAD

**Issue by rchaser53** [eawsy/aws-lambda-go-shim#51]
i want to use environment variable to post the message to slack.
so i add the environment variable like below in Makefile.

``` Makefile
docker:
	docker run --rm\
		-e SlackUrl=$(SlackUrl)\
		-e HANDLER=$(HANDLER)\
		-e PACKAGE=$(PACKAGE)\
		-e GOPATH=$(GOPATH)\
		-e LDFLAGS='$(LDFLAGS)'\
		-v $(CURDIR):$(CURDIR):Z\
		$(foreach GP,$(subst :, ,$(GOPATH)),-v $(GP):$(GP)):Z\
		-w $(CURDIR)\
		eawsy/aws-lambda-go-shim:latest make -f $(MAKEFILE) all
```

and use like below. but get empty.

``` golang
url := os.Getenv("SlackUrl")  // url is ""
```

how should i do?

**Comment by fsenart** [comment]
Hi @rchaser53,

In order to use environment variables inside your Lambda code, you don't have to do anything special. You just have to [configure your Lambda function](https://docs.aws.amazon.com/lambda/latest/dg/env_variables.html#env_setting_up) (by cli or by the web console). So do not modify your Makefile.

**Comment by rchaser53** [comment]
oh. it's no relation for this module.
it worked. thank you for that!
